version: "3"

services:
  app:
    container_name: app
    build: ./docker/php
    tty: true
    volumes:
      - .:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    tty: true
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dental-manage
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true
    volumes:
      - dental-manage-data:/var/lib/mysql
    ports:
      - 3306:3306

  # node:
  #   image: node:16-alpine
  #   container_name: node
  #   working_dir: /var/www
  #   command: ["npm", "run", "build"]
  #   tty: true
  #   volumes:
  #     - ./src:/var/www

volumes:
  dental-manage-data:
# version: "3"
# services:
#   app:
#     container_name: app
#     build: ./docker/php
#     volumes:
#       - .:/var/www
#   nginx:
#     image: nginx
#     container_name: nginx
#     ports:
#       - 8000:80
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     working_dir: /var/www
#     depends_on:
#       - app
#   db:
#     image: mysql:5.7
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: database
#       MYSQL_USER: db-user
#       MYSQL_PASSWORD: db-pass
#       TZ: "Asia/Tokyo"
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - dental-manage-data:/var/lib/mysq
#     ports:
#       - 3306:3306

#   node:
#     image: node:12.13-alpine
#     container_name: node
#     tty: true
#     volumes:
#       - ./src:/var/www
#     working_dir: /var/www

# volumes:
#   dental-manage-data:
